---

- name: Prepare directory structure
  file:
    src: "{{ item }}"
    dest: "{{ ovirt_collect_logs_tmp_dir }}/{{ item }}"
    state: directory
  with_items:
    - "etc"

- name: Register coredump path
  shell: "cat /proc/sys/kernel/core_pattern | xargs dirname | head -n 1"
  register: coredumpdir

- name: Link vdsm and libvirt logs
  file:
    src: "{{ item.src }}"
    dest: "{{ ovirt_collect_logs_tmp_dir }}/{{ item.dest }}"
    state: link
  with_items:
    -
      src: "/var/log/vdsm"
      dest: "vdsm-logs"
    -
      src: "/var/log/libvirt"
      dest: "libvirt-logs"
    -
      src: "/etc/ovirt-vmconsole"
      dest: "etc/ovirt-vmconsole"
    -
      src: "/etc/vdsm"
      dest: "etc/vdsm"
    -
      src: "/etc/libvirt"
      dest: "etc/libvirt"
    -
      src: "/var/log/ovirt-hosted-engine-setup"
      dest: "hosted-engine-setup-logs"
    -
      src: "/var/log/ovirt-hosted-engine-ha"
      dest: "hosted-engine-logs"
    -
      src: "{{ coredumpdir }}"
      dest: "coredumps"
    -
      src: "/var/log/ovirt-imageio-daemon"
      dest: "ovirt-imageio-daemon-logs"
  ignore_errors: true

- name: Dump mount
  shell: "mount &> {{ ovirt_collect_logs_tmp_dir }}/mount.txt"
  ignore_errors: true

- name: Dump multipath
  shell: "multipath -ll &> {{ ovirt_collect_logs_tmp_dir }}/multipath.txt"
  ignore_errors: true

- name: Dump lvm
  shell: "(vgs; pvs; lvs) &> {{ ovirt_collect_logs_tmp_dir }}/lvm.txt"
  ignore_errors: true
